config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  resources :tips
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match 'options', to: 'static_pages#options', as: 'options', via: [:get, :post]

end

app/models/tip.rb
class Tip < ActiveRecord::Base
	default_scope -> { order('created_at Desc')}
	searchkick

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  include SessionsHelper

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to options_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :signed_in_user, only: :options

	def home
		if signed_in?
			render :options
		end
  	end

	def options
		
	end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
	before_action :signed_in_user

  def index
  	@tips =Tip.all
  end

  def new
  	@tip = Tip.new
  end


  def create
  	@tip = Tip.new(user_params)
  	if @tip.save
  		flash[:success] = "Tip successfully saved!"
  		redirect_to action: 'index' 
  	else
  		render 'new'
  	end
  end

  private

    def user_params
      params.require(:tip).permit(:tip, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def signed_in_user
	  unless signed_in?
	      store_location
	      redirect_to root_url, notice: "Please sign in."
	  end
	end	

		def signed_in?
		!current_user.nil?
		end

		def store_location
     	session[:return_to] = request.url if request.get?
  	end	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traveltip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
	<script type="text/javascript" src="/assets/jquery.geocomplete.js"></script>
  </head>
<body>

<div >
	<% if current_user %>
	    Welcome <strong><%= current_user.name %></strong>!
	    
	    <%= link_to "Sign out", signout_path, id: "sign_out", style:"float:right;padding-right:20px;" %>

	    <%= link_to "Home", options_path, style:"float:right;padding-right:20px;" %>

	<%end%>    
</div>
	
	
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="wrapper">
  <div class="bg-overlay">
    <div class="container">
     <div class = "tag-position">
     <%= link_to image_tag("facebook-icon.png",class: "fb-icon"), "/auth/facebook", id: "sign_in" %>
      </div>

      <div class="homebanner ">
      	<h1>Tips for Travelers, Tips from Travelers</h1>
      </div>
     
    </div>
  </div>
</div>

app/views/static_pages/options.html.erb
<div style="width:200px; margin:0 auto;padding-top:150px;">

	<%= link_to "Add a Tip", new_tip_path, class: "btn btn-primary btn-lg btn-block" %>

	<%= link_to "Search a Tip", tips_path, class: "btn btn-default btn-lg btn-block"%>

</div>

app/views/tips/index.html.erb
<%= form_tag(tips_path, :location => "get", id: "search-form") do %>
  <%= text_field_tag :location, params[:location], placeholder: "Search Tips ",id: "searchlocation" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<div style="padding-top:50px;">
	<h2 style="text-align:center;padding-bottom:30px">All Tips</h2>

	<ul class="tips"> 
	  <% @tips.each do |tip| %>
	    <li class="list-group-item" style="margin-right:40px;">
	      <h4 class="list-group-item-heading"><%= tip.location %></h4>
	      <p class="list-group-item-text"><%= tip.tip %></p>
	    </li>	
	  <% end %>
	</ul>
</div>

app/views/tips/new.html.erb
<h2 class="text-center"> Create a tip </h1>
<div class="container">
	<div class="row" id="login-container">
  <div class="">
    <%= form_for(@tip) do |f| %>

      <%= f.label :tip%>
      <%= f.text_area :tip, class: "form-control", rows: "3",placeholder: "Enter tip Less than 201 characters"%>
      <%= f.label :location, style: "margin-top:20px" %>
		<input  class="form-control" id="tiplocation" placeholder="Enter your address" name="tip[location]"
	             type="text"></input>


      <%= f.submit "Enter tip", class: "btn btn-large btn-primary", style: "margin-top:40px" %>
    <% end %>
  </div>
</div>